### PR TITLE
Display warning banner on test sites

### PR DESCRIPTION
**Pull request by liamjohnston**
From a discussion here:
https://springload.slack.com/archives/C06P11WJD5Z/p1717447908586899

Warning, some BED-by-FED going on here 👀 

We also would want this to display on the pre-prod site (if that's a thing?). 

What suggestions have you, @haydngreatnews / @sarahframe ?

### CODE REVIEW

**Comment by liamjohnston** [comment]
Hmm, actually it's showing on my local, which it is not meant to, so I guess I've missed a step somewhere...

**Comment by liamjohnston** [comment]
Seemingly working now after making a `.env` and referencing it.

**Review by haydngreatnews — COMMENTED** [review]
This seems fine -- I'll just need to have a look at how the existing hosting deals with envvars

**Comment by haydngreatnews** [comment]
No envvars in their current hosting configuration, but they do already have an existing setting -- `SHOW_TEST_WARNING`, which is what has been used previously, so I've refactored to use that instead

**Review by haydngreatnews — APPROVED** [review]

**Pull request merged**
